[package]
name = "fmt-log"
version = "0.1.0"
edition = "2021"
description = "Macros for logging to the console, but also returning the formatted string"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
